name: draw_my_travel
description: Draw your travel

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.7.0+2
  path_provider: ^1.2.0
  json_annotation: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  json_serializable: ^3.1.0

flutter:
  uses-material-design: true